name: CI/CD Pipeline for DBT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake

    - name: Configure Snowflake Profile
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      run: |
        mkdir -p ~/.dbt
        echo "stocks_data:
          outputs:
            dev:
              type: snowflake
              account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
              user: ${{ secrets.SNOWFLAKE_USER }}
              password: \"${{ secrets.SNOWFLAKE_PASSWORD }}\"
              role: ${{ secrets.SNOWFLAKE_ROLE }}
              warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
              database: ${{ secrets.SNOWFLAKE_DATABASE }}
              schema: STAGE
          target: dev" > ~/.dbt/profiles.yml

    - name: Print profiles.yml
      run: cat ~/.dbt/profiles.yml

    - name: Run DBT Commands
      run: |
        dbt debug
        dbt run
        dbt test